%temperature in degrees Celsius
%frequency in MHz

function queryYIGstatus(yig.obj)

yig = open_instrument_connection_generic('YIG 2')

yig_status = struct('model_number',query(yig.obj,'R000?'),...
    'serial_number',query(yig.obj,'R0001?'),...
    'IP_address',query(yig.obj,'R0101?'),...
    'firmware_version_date',query(yig.obj,'R0012?'),...
    'unit_health_status',query(yig.obj,'R0013?'),...
    'self_test_results',query(yig.obj,'R0015?'),...
    'unit_calibration_status',query(yig.obj,'R0014?'),...
    'min_freq',query(yig.obj,'R0003?'),...
    'max_freq',query(yig.obj,'R0004?'),...
    'current_freq',query(yig.obj,'R0016?'),...
    'min_temp',query(yig.obj,'R0008?'),...
    'max_temp',query(yig.obj,'R0009?'),...
    'highest_temp_reached',query(yig.obj,'R0010?'))
end
